services:
  # Mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  # Wordpress
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped
  
  # Nginx
  nginx:
    ports:
      - "443:443"
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
   
  adminer:
    build: ./requirements/adminer
    container_name: adminer
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
  
  vsftpd:
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    env_file:
      - .env
    build: ./requirements/vsftpd
    container_name: vsftpd
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped

  redis:
    build: ./requirements/redis
    container_name: redis
    networks:
      - inception
    restart: unless-stopped

# Volumes
volumes:
  mariadb_data: #Volume docker
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/daniel/data/mariadb # data stored in the host
  wordpress_data:   
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/daniel/data/wordpress

# Networks 
networks:
  inception:
    driver: bridge